changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - github-actions[bot]
  categories:
    - title: "Perbaikan"
      labels:
        - fix
        - bug
        - hotfix
    - title: "Peningkatan"
      labels:
        - enhancement
        - improvement
        - perf
        - refactor
    - title: "Dokumentasi"
      labels:
        - docs
    - title: "Lainnya"
      labels:
        - "*"
